src = ["casino"]
line-length = 150
respect-gitignore = true

[lint]
# ambiguous-variable-name
ignore = ["E741", "E501"]

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "single"
exclude = [
    "abstract.py",  "cusp.py",  "gjastrow.py",  "loggers.py",  "overload.py",  "ppotential.py",  "pycasino.py",  "sem.py",
    "backflow.py",  "dmc.py",   "harmonics.py",  "jastrow.py",   "mpi.py",      "slater.py",  "wfn.py"
]
