src = ["casino"]
line-length = 120
respect-gitignore = true

[lint]
# ambiguous-variable-name
ignore = ["E741", "F841", "F821"]

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "single"
