#!/bin/bash

# path='tests/gwfn/He/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/Be/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/N/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/Ne/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/Ar/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/Kr/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/O3/HF/cc-pVQZ/CBCS/Slater/'
# path='tests/gwfn/B2H6/HF/cc-pVQZ/CBCS/Slater/'

# path='tests/gwfn/He/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/Be/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/N/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/Ne/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/Ar/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/Kr/HF/cc-pVQZ/CBCS/Jastrow/'
# path='tests/gwfn/O3/HF/cc-pVQZ/CBCS/Jastrow/'

# path='tests/gwfn/He/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/Be/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/N/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/Ne/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/Ar/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/Kr/HF/cc-pVQZ/CBCS/Backflow/'
# path='tests/gwfn/O3/HF/cc-pVQZ/CBCS/Backflow/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Slater/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Slater/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Jastrow_varmin/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Jastrow_emin/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Jastrow_emin/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Backflow_varmin/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Backflow_varmin/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Backflow_emin/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Backflow_emin/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Jastrow/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Jastrow/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Backflow/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Backflow/'

# path='tests/stowfn/He/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/Be/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/N/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/Ne/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/Ar/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/Kr/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='tests/stowfn/O3/HF/QZ4P/CBCS/Jastrow_dmc/'

# python pycasino/casino.py $path
# mpiexec python pycasino/casino.py $path

# pycasino/profiling.py
