#!/bin/bash

# path='gwfn/He/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/Be/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Slater/'
# path='gwfn/N/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/Ne/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/Ar/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/Kr/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/O3/HF/cc-pVQZ/CBCS/Slater/'
# path='gwfn/B2H6/HF/cc-pVQZ/CBCS/Slater/'

# path='gwfn/He/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/Be/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/N/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/Ne/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/Ar/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/Kr/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/O3/HF/cc-pVQZ/CBCS/Jastrow/'
# path='gwfn/B2H6/HF/cc-pVQZ/CBCS/Jastrow/'

# path='gwfn/He/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/Be/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/N/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/Ne/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/Ar/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/Kr/HF/cc-pVQZ/CBCS/Backflow/'
# path='gwfn/O3/HF/cc-pVQZ/CBCS/Backflow/'

# path='gwfn/He/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/Be/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/Be/MP2-CASSCF(2.4)/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/N/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/Ne/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/Ar/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/Kr/HF/cc-pVQZ/CBCS/Jastrow_varmin/'
# path='gwfn/O3/HF/cc-pVQZ/CBCS/Jastrow_varmin/'

# path='stowfn/He/HF/QZ4P/CBCS/Slater/'
# path='stowfn/Be/HF/QZ4P/CBCS/Slater/'
# path='stowfn/N/HF/QZ4P/CBCS/Slater/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Slater/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Slater/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Slater/'
# path='stowfn/O3/HF/QZ4P/CBCS/Slater/'

# path='stowfn/He/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/Be/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/N/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Jastrow/'
# path='stowfn/O3/HF/QZ4P/CBCS/Jastrow/'

# path='stowfn/He/HF/QZ4P/CBCS/Gjastrow/'
# path='stowfn/Be/HF/QZ4P/CBCS/Gjastrow/'

# path='stowfn/He/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/Be/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/N/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Backflow/'
# path='stowfn/O3/HF/QZ4P/CBCS/Backflow/'

# path='stowfn/He/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/Be/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/N/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Jastrow_dmc/'
# path='stowfn/O3/HF/QZ4P/CBCS/Jastrow_dmc/'

# path='stowfn/He/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/Be/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/N/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Backflow_dmc/'
# path='stowfn/O3/HF/QZ4P/CBCS/Backflow_dmc/'

# path='stowfn/He/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/Be/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/N/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Jastrow_varmin/'
# path='stowfn/O3/HF/QZ4P/CBCS/Jastrow_varmin/'

# path='stowfn/He/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/Be/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/N/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Jastrow_emin/'
# path='stowfn/O3/HF/QZ4P/CBCS/Jastrow_emin/'

# path='stowfn/He/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/Be/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/N/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/Ne/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/Ar/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/Kr/HF/QZ4P/CBCS/Backflow_varmin/'
# path='stowfn/O3/HF/QZ4P/CBCS/Backflow_varmin/'

# path='stowfn/He/HF/QZ4P/CBCS/Backflow_emin/'
# path='stowfn/Be/HF/QZ4P/CBCS/Backflow_emin/'

# pycasino $path
# mpiexec pycasino $path

# pycasino_profiling.py
